### ISSUE TITLE
No semicolons support

### ISSUE THREAD

**Issue by mxstbr** [thysultan/stylis.js#12]
I'm working on a big app with lots of CSS, and tried to use `styled-components` v2 but everything broke. After some debugging I realised that almost all of the breakage was because we're not very... consistent with semicolons, and `stylis` treats semicolon-less lines differently from PostCSS.

Is there any chance we could align that behaviour? Otherwise few people can upgrade to v2 as it'll break their entire app with basically no automated way of fixing it. :confused:

**Comment by thysultan** [comment]
Maybe it's just a matter of adding newlines to the break tokens, can you give me an example case i can work with?

**Comment by mxstbr** [comment]
Literally copy and paste:

```JS
p {
		background-color: ${props =>
  props.me ? props.theme.brand.default : props.theme.generic.default};
		background-image: ${props =>
  props.me
    ? Gradient(props.theme.brand.alt, props.theme.brand.default)
    : Gradient(props.theme.generic.alt, props.theme.generic.default)}
		color: ${props =>
  props.me ? props.theme.text.reverse : props.theme.text.default};
		align-self: ${props => props.me ? `flex-end;` : `flex-start;`}
		font-weight: ${props => props.me ? `500` : `400`};
		clear: both;

		&::selection {
		  background-color: ${props =>
  props.me ? props.theme.text.default : props.theme.brand.alt};
}
	}
```

Output:

![screen shot 2017-03-30 at 17 17 46](https://cloud.githubusercontent.com/assets/7525670/24511723/d5104c54-156c-11e7-863b-55d0e522734c.png)

Note how it doesn't separate the `background-image` `Gradient` stuff from the `color` on the next line.

**Comment by thysultan** [comment]
Have been playing around with an implementation, the hard part is also supporting flat css, will look more into it.

**Comment by thysultan** [comment]
For a simple solution that supports both flat and nested css the main problem i can see is differentiating the following

```css
h1:active
{
color:red;
}

// and
color: red
``` 
Other artifacts are easier to reason about their intent but the `h1:active` looks like a property `color:red` if you remove the need for a `;` token to mark the end of a property, considering there is no context of the future. On the other hand this can be solved by introducing a concept of the distant future where the parser builds up two buffers one that represents what will be processed and another that will be processed after, this way you can know that `h1:active` is a selector and `color:red` is a property by the context that `h1:active` is followed by `{` token, i'll play with this idea a bit more.

**Comment by thysultan** [comment]
I think i've got hit on a solution but it won't be in stylis v2.0.0

**Comment by mxstbr** [comment]
That'd be super awesome! I'd be interested to hear what the difference in the parser has to be. :blush:

**Comment by thysultan** [comment]
Sure, so since
```
button:hover

{}

// looks like

color:red
```

a possible solution is to register whenever a `:` character is present in the current buffer, when a newline is found after the characters following `:`, fast foward to just before the next non-whitespace character then look ahead `index+1` to see if the next character is indeed a `{` character. If it is not then it can safely auto insert a semicolon, if it is then continue as normal. This [https://github.com/thysultan/stylis.js/blob/master/experiments/no-semicolons.js#L1085](https://github.com/thysultan/stylis.js/blob/master/experiments/no-semicolons.js#L1085) with a few changes.

**Comment by mxstbr** [comment]
Super interesting! Does this have some negative performance implications since we're now doing a lookahead more than before?

**Comment by thysultan** [comment]
The idea is that it shouldn't since we are still doing the same thing.. moving the caret position forward and building a buffer. The normal path gets the current non-whitespace* character and current character code, this path gets the current non-whitespace character and next character code so the # of ops are roughly equal.

* newlines and tabs.

**Comment by thysultan** [comment]
BTW this is implemented in [V3](https://github.com/thysultan/stylis.js/tree/master/rewrite), haven't yet release it though.

**Comment by thysultan** [comment]
V3 supports no semicolons
