### ISSUE TITLE
Investigate grouping media queries together

### ISSUE THREAD

**Issue by kripod** [thysultan/stylis.js#136]
The size of generated bundles can be reduced by [grouping media queries together](https://stackoverflow.com/questions/11626174/is-there-an-advantage-in-grouping-css-media-queries-together). For example, the following snippet:

```js
const Box = styled.div`
  :hover {
    @media (min-width: 600px) {
      color: red;
    }
  }

  :first {
    @media (min-width: 600px) {
      color: blue;
    }
  }
`;
```

Could be transformed into the following code during build (possibly by Babel):

```js
const Box = styled.div`
  @media (min-width: 600px) {
    :hover {
      color: red;
    }

    :first {
      color: blue;
    }
  }
`;
```

---

_(This issue is a cross-post of https://github.com/styled-components/styled-components/issues/2310)_

**Comment by thysultan** [comment]
Like the StackOverflow answer mentions the savings considering gzip(if you're server-side rendering) seem negligible assuming reasonable use of media-queries.

That said stylis doesn't hook into Babel, so this might be unrelated to the stylis itself.

Have you come across issues related to the generated output due to media-queries?

**Comment by Andarist** [comment]
This is out of the scope of the stylis. It's meant as a minimal parser implementation and doesn't perform any optimizations like this.
