### ISSUE TITLE
Syntax errors

### ISSUE THREAD

**Issue by k15a** [thysultan/stylis.js#2]
Would be great if we could get some syntax errors for invalid CSS. Is this possible with stylis?

**Comment by thysultan** [comment]
stylis doesn't lint, but you can run a linter on the output/input or on the javascript - [http://mxstbr.blog/2016/12/linting-styles-in-js-with-stylelint/](http://mxstbr.blog/2016/12/linting-styles-in-js-with-stylelint/)

**Comment by thysultan** [comment]
but i'm currently working on adding middleware support for v0.9.0 so you can make a plugin for this.

**Comment by k15a** [comment]
Thank you.

**Comment by thysultan** [comment]
@k15a stylis now supports [middleware](https://github.com/thysultan/stylis.js#middleware) that are executed at different cycles(begin, block, line, selector, property, complete), so someone could build a plugin that acts as a [linter](https://github.com/csstree/csstree), though i doubt there can be a one size fits all linter since you can very drastically re-shape the syntax of css to support custom functions and more with middleware.
