### ISSUE TITLE
Should color-adjust be prefixed?

### ISSUE THREAD

**Issue by oliviertassinari** [thysultan/stylis.js#210]
The behavior of this CSS property is described in [color-adjust](https://www.w3.org/TR/css-color-adjust-1/#perf). This property could potentially be prefixed with [-webkit-print-color-adjust](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-print-color-adjust). Would it make sense to support it here?

**Comment by Andarist** [comment]
Is this a standard property? I see it being supported in FireFox without any prefixes, but I'm not sure how to interpret linked spec. I'm not too familiar with CSS standardization process and thus I'm not sure what's the current status of this one.

**Comment by eps1lon** [comment]
According to MDN `color-adjust` is implemented in chromium with the `-webkit` prefix: https://developer.mozilla.org/en-US/docs/Web/CSS/color-adjust#Browser_compatibility

**Comment by Andarist** [comment]
Right, I'm interested if this is a standard feature that needs prefixing to work in some browsers, or is it a non-standard property that comes prefixed and non-prefixed in some browsers. As far as I can tell we currently support prefixing only of standard properties.

**Comment by eps1lon** [comment]
The link to the spec was already linked as well as MDN explaining how -webkit-print-color-adjust is non-standard while color-adjust is. Do you meant that you don't prefix editor drafts? What is the minimum stage you start prefixing properties?

**Comment by Andarist** [comment]
> Do you meant that you don't prefix editor drafts?

I'm not 100% sure, but I think there are no editor draft properties prefixed right now. From what I understand editor draft is the very beginning of the standardization process - so I'm not sure if we want to support this. Keep in mind that every added property adds to the bundle size. 

> What is the minimum stage you start prefixing properties?

I'm not against adding this per se, but there is currently no rule of thumb which properties we should strive to support and which we shouldn't. So this issue is definitely a good time to decide about this one and probably add a note about it to the docs. @thysultan what's your opinion on this matter?
