### ISSUE TITLE
[rule-sheet plugin] invalid rules after at-rule

### ISSUE THREAD

**Issue by giuseppeg** [thysultan/stylis.js#65]
this string

```js
'span { color: red } @font-face { font-family: test; src: url(test.woff); } div { color: red }'
```
is split into this:

```js
[ '@font-face{font-family:test;src:url(test.woff);}',
  'span{color:red;}',
  '@font-face{font-family:test;src:url(test.woff);}div{color:red;}' ]
```

the last item should be `div{color:red;}`

My version of the plugin fixes this https://github.com/zeit/styled-jsx/blob/master/src/lib/style-transform.js#L82

**Comment by thysultan** [comment]
Thanks, i've published a patch for this.

**Comment by giuseppeg** [comment]
@thysultan it seems that your version of the plugin alterates the order of the rules which I think might lead to specificity bugs. This is the output with `stylis-rule-sheet`:

```
[ '@font-face{font-family:test;src:url(test.woff);}',
  'span{color:red;}',
  'div{color:red;}' ]
```

The `@font-face` rule should be at index 1:

```
[ 'span{color:red;}',
  '@font-face{font-family:test;src:url(test.woff);}',
  'div{color:red;}' ]
```

**Comment by thysultan** [comment]
@giuseppeg It is intentional – all at-rules that do not affect the cascade/specificity are processed first, this means `@import` is also treating like this. But they still appear in the order they where defined, i.e two `@font-face` will appear in the right order in which they where defined, so specificity within the same at-rules should not be a problem.

It also means `@import, @supports, @keyframes` are excluded.

It's done like this because some `@at-rules` require that they are added first i.e `@import` otherwise insertRule will throw.

**Comment by giuseppeg** [comment]
ok I wanted to check with you, mainly I was thinking of @media
